In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
myyear = 2026
mymont=1
myday=1
myhour=2
mymin=30
mysec=29

In [6]:
from datetime import datetime
mydate = datetime(myyear, mymont, myday)
mydate

datetime.datetime(2026, 1, 1, 0, 0)

In [8]:
mydatetime= datetime(myyear, mymont, myday, myhour, mymin, mysec)
mydatetime

datetime.datetime(2026, 1, 1, 2, 30, 29)

In [9]:
sales = pd.read_csv('Retail Sales.csv')
sales

          DATE  Sales
0     1/1/1992   1509
1     2/1/1992   1541
2     3/1/1992   1597
3     4/1/1992   1675
4     5/1/1992   1822
..         ...    ...
347  12/1/2020   7366
348   1/1/2021   5087
349   2/1/2021   4968
350   3/1/2021   5727
351   4/1/2021   5712

[352 rows x 2 columns]

In [16]:
sales['DATE'] = pd.to_datetime(sales['DATE'])
sales

          DATE  Sales
0   1992-01-01   1509
1   1992-02-01   1541
2   1992-03-01   1597
3   1992-04-01   1675
4   1992-05-01   1822
..         ...    ...
347 2020-12-01   7366
348 2021-01-01   5087
349 2021-02-01   4968
350 2021-03-01   5727
351 2021-04-01   5712

[352 rows x 2 columns]

In [18]:
sales['DATE']

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
347   2020-12-01
348   2021-01-01
349   2021-02-01
350   2021-03-01
351   2021-04-01
Name: DATE, Length: 352, dtype: datetime64[ns]

In [21]:
sales['DATE'][0]

Timestamp('1992-01-01 00:00:00')

In [22]:
sales.head()

        DATE  Sales
0 1992-01-01   1509
1 1992-02-01   1541
2 1992-03-01   1597
3 1992-04-01   1675
4 1992-05-01   1822