In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('tips.csv')

In [5]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [10]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [13]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [16]:
df = df.set_index("total_bill")

In [17]:
df

             tip     sex smoker   day    time  size
total_bill
16.99       1.01  Female     No   Sun  Dinner     2
10.34       1.66    Male     No   Sun  Dinner     3
21.01       3.50    Male     No   Sun  Dinner     3
23.68       3.31    Male     No   Sun  Dinner     2
24.59       3.61  Female     No   Sun  Dinner     4
...          ...     ...    ...   ...     ...   ...
29.03       5.92    Male     No   Sat  Dinner     3
27.18       2.00  Female    Yes   Sat  Dinner     2
22.67       2.00    Male    Yes   Sat  Dinner     2
17.82       1.75    Male     No   Sat  Dinner     2
18.78       3.00  Female     No  Thur  Dinner     2

[244 rows x 6 columns]

In [18]:
df.iloc[0]

tip         1.01
sex       Female
smoker        No
day          Sun
time      Dinner
size           2
Name: 16.99, dtype: object

In [22]:
df.iloc[5]

tip         4.71
sex         Male
smoker        No
day          Sun
time      Dinner
size           4
Name: 25.29, dtype: object

In [ ]:
df.drop('size')