In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df[df['tip']>5]

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [7]:
df[df['tip']>=5]

     total_bill    tip     sex smoker   day    time  size
11        35.26   5.00  Female     No   Sun  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
73        25.28   5.00  Female    Yes   Sat  Dinner     2
83        32.68   5.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
185       20.69   5.00    Male     No   Sun  Dinner     5
197       43.11   5.00  Female    Yes  Thur   Lunch     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [12]:
df[df['tip']<=1.5]

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
30         9.55  1.45    Male     No   Sat  Dinner     2
43         9.68  1.32    Male     No   Sun  Dinner     2
57        26.41  1.50  Female     No   Sat  Dinner     2
67         3.07  1.00  Female    Yes   Sat  Dinner     1
75        10.51  1.25    Male     No   Sat  Dinner     2
92         5.75  1.00  Female    Yes   Fri  Dinner     2
97        12.03  1.50    Male    Yes   Fri  Dinner     2
99        12.46  1.50    Male     No   Fri  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
117       10.65  1.50  Female     No  Thur   Lunch     2
126        8.52  1.48    Male     No  Thur   Lunch     2
130       19.08  1.50    Male     No  Thur   Lunch     2
132       11.17  1.50  Female     No  Thur   Lunch     2
135        8.51  1.25  Female     No  Thur   Lunch     2
145        8.35  1.50  Female     No  Thur   Lunch     2
146       18.64  1.36  Female     No  Thur   Lunch     3
190       15.69  1.50    Male    Yes   Sun  Dinner     2
195        7.56  1.44    Male     No  Thur   Lunch     2
215       12.90  1.10  Female    Yes   Sat  Dinner     2
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2

In [13]:
bool_series = df['tip']>5

In [14]:
df[bool_series]

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [23]:
 df[(df['tip'] > 5) & (df['sex']=='Male')]

     total_bill    tip   sex smoker   day    time  size
23        39.42   7.58  Male     No   Sat  Dinner     4
44        30.40   5.60  Male     No   Sun  Dinner     4
47        32.40   6.00  Male     No   Sun  Dinner     4
59        48.27   6.73  Male     No   Sat  Dinner     4
88        24.71   5.85  Male     No  Thur   Lunch     2
116       29.93   5.07  Male     No   Sun  Dinner     4
141       34.30   6.70  Male     No  Thur   Lunch     6
170       50.81  10.00  Male    Yes   Sat  Dinner     3
172        7.25   5.15  Male    Yes   Sun  Dinner     2
181       23.33   5.65  Male    Yes   Sun  Dinner     2
183       23.17   6.50  Male    Yes   Sun  Dinner     4
211       25.89   5.16  Male    Yes   Sat  Dinner     4
212       48.33   9.00  Male     No   Sat  Dinner     4
239       29.03   5.92  Male     No   Sat  Dinner     3

In [25]:
 df[(df['tip'] > 5) | (df['sex'] =='Female')]

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[101 rows x 7 columns]

In [26]:
 df[(df['tip'] > 5) | (df['sex'] =='Female') & (df['day'] == 'Sun')]

     total_bill    tip     sex smoker   day    time  size
0         16.99   1.01  Female     No   Sun  Dinner     2
4         24.59   3.61  Female     No   Sun  Dinner     4
11        35.26   5.00  Female     No   Sun  Dinner     4
14        14.83   3.02  Female     No   Sun  Dinner     2
16        10.33   1.67  Female     No   Sun  Dinner     3
18        16.97   3.50  Female     No   Sun  Dinner     3
23        39.42   7.58    Male     No   Sat  Dinner     4
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
51        10.29   2.60  Female     No   Sun  Dinner     2
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
114       25.71   4.00  Female     No   Sun  Dinner     3
115       17.31   3.50  Female     No   Sun  Dinner     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
157       25.00   3.75  Female     No   Sun  Dinner     4
158       13.39   2.61  Female     No   Sun  Dinner     2
162       16.21   2.00  Female     No   Sun  Dinner     3
164       17.51   3.00  Female    Yes   Sun  Dinner     2
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
178        9.60   4.00  Female    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
186       20.90   3.50  Female    Yes   Sun  Dinner     3
188       18.15   3.50  Female    Yes   Sun  Dinner     3
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [31]:
str(123112323124)[-8:]

'12323124'